#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : php-json_post
Version  : 1.0.2
Release  : 7
URL      : https://pecl.php.net/get/json_post-1.0.2.tgz
Source0  : https://pecl.php.net/get/json_post-1.0.2.tgz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: php-json_post-lib = %{version}-%{release}
BuildRequires : buildreq-php

%description
# ext-json_post
[![Build Status](https://travis-ci.org/m6w6/ext-json_post.svg?branch=master)](https://travis-ci.org/m6w6/ext-json_post)

%package lib
Summary: lib components for the php-json_post package.
Group: Libraries

%description lib
lib components for the php-json_post package.


%prep
%setup -q -n json_post-1.0.2
cd %{_builddir}/json_post-1.0.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
phpize
%configure
make  %{?_smp_mflags}

%install
%make_install


%files
%defattr(-,root,root,-)

%files lib
%defattr(-,root,root,-)
/usr/lib64/extensions/no-debug-non-zts-20190902/json_post.so
